# Part B :- Classification


In [1]:

import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt

df=pd.read_csv(r'C:\Users\aa\OneDrive\Documents\Mechanical Engineering\sem 1 2020-21\IME672A\Project/covid.csv')

for i in df.columns:
    if i in ['id','entry_date','date_symptoms','date_died','age']:
        continue
    else:
        print('unique values in '+ i +' column- ',end=' ')
        print(df[i].unique())

date_cols=['entry_date','date_symptoms']
for dates in date_cols:
    df[dates]=pd.to_datetime(df[dates],infer_datetime_format=True)

df1=df
df['date_died'].replace('9999-99-99','Not Applicable',inplace=True)

df=df[['sex', 'patient_type', 'entry_date', 'date_symptoms', 'date_died', 'age',
       'intubed', 'pneumonia', 'pregnancy', 'diabetes', 'copd',
       'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular',
       'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid',
       'covid_res', 'icu']]

df.iloc[:,6:]=df.iloc[:,6:].replace([97,98,99],np.nan)
df.iloc[:,6:]=df.iloc[:,6:].replace(1,'Yes')
df.iloc[:,6:]=df.iloc[:,6:].replace(2,'No')

df.iloc[:,-2]=df.iloc[:,-2].replace('Yes','Positive')
df.iloc[:,-2]=df.iloc[:,-2].replace('No','Negative')
df.iloc[:,-2]=df.iloc[:,-2].replace(3,'Results awaited')

df=df[df['covid_res']!='Results awaited']

df

unique values in sex column-  [2 1]
unique values in patient_type column-  [1 2]
unique values in intubed column-  [97  2  1 99]
unique values in pneumonia column-  [ 2  1 99]
unique values in pregnancy column-  [97  2  1 98]
unique values in diabetes column-  [ 2  1 98]
unique values in copd column-  [ 2  1 98]
unique values in asthma column-  [ 2  1 98]
unique values in inmsupr column-  [ 2  1 98]
unique values in hypertension column-  [ 2  1 98]
unique values in other_disease column-  [ 2  1 98]
unique values in cardiovascular column-  [ 2  1 98]
unique values in obesity column-  [ 2  1 98]
unique values in renal_chronic column-  [ 2  1 98]
unique values in tobacco column-  [ 2  1 98]
unique values in contact_other_covid column-  [ 2 99  1]
unique values in covid_res column-  [1 2 3]
unique values in icu column-  [97  2  1 99]


C:\Users\aa\Anaconda3_2020\lib\site-packages\pandas\core\indexing.py:1717: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, v)
C:\Users\aa\Anaconda3_2020\lib\site-packages\pandas\core\indexing.py:1745: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


sex  patient_type entry_date date_symptoms       date_died  age  \
0         2             1 2020-04-05    2020-02-05  Not Applicable   27   
1         2             1 2020-03-19    2020-03-17  Not Applicable   24   
2         1             2 2020-06-04    2020-01-04  Not Applicable   54   
3         2             2 2020-04-17    2020-10-04  Not Applicable   30   
4         1             2 2020-04-13    2020-04-13      22-04-2020   60   
...     ...           ...        ...           ...             ...  ...   
499687    2             1 2020-03-26    2020-03-20  Not Applicable   77   
499688    2             2 2020-03-28    2020-03-23  Not Applicable   63   
499689    1             1 2020-03-16    2020-03-13  Not Applicable   25   
499690    1             1 2020-03-27    2020-03-25  Not Applicable   45   
499691    1             1 2020-03-31    2020-03-23  Not Applicable   51   

       intubed pneumonia pregnancy diabetes  ... inmsupr hypertension  \
0          NaN        No       NaN       No  ...      No           No   
1          NaN        No       NaN       No  ...      No           No   
2           No        No        No       No  ...      No           No   
3           No       Yes       NaN       No  ...      No           No   
4           No        No        No      Yes  ...      No          Yes   
...        ...       ...       ...      ...  ...     ...          ...   
499687     NaN       Yes       NaN       No  ...      No           No   
499688     Yes       Yes       NaN       No  ...      No          Yes   
499689     NaN        No        No       No  ...      No           No   
499690     NaN        No        No       No  ...      No          Yes   
499691     NaN        No        No       No  ...      No           No   

       other_disease cardiovascular obesity renal_chronic tobacco  \
0                 No             No      No            No      No   
1                 No             No      No            No      No   
2                 No             No     Yes            No      No   
3                 No             No      No            No      No   
4                 No            Yes      No            No      No   
...              ...            ...     ...           ...     ...   
499687           Yes             No      No            No     Yes   
499688            No             No     Yes            No     Yes   
499689            No             No      No            No      No   
499690            No             No      No            No      No   
499691            No             No      No            No      No   

       contact_other_covid covid_res  icu  
0                       No  Positive  NaN  
1                      NaN  Positive  NaN  
2                      NaN  Positive   No  
3                      NaN  Positive   No  
4                      NaN  Positive   No  
...                    ...       ...  ...  
499687                  No  Negative  NaN  
499688                  No  Negative   No  
499689                  No  Negative  NaN  
499690                 Yes  Negative  NaN  
499691                 NaN  Negative  NaN  

[499692 rows x 22 columns]

In [2]:
df.columns


Index(['sex', 'patient_type', 'entry_date', 'date_symptoms', 'date_died',
       'age', 'intubed', 'pneumonia', 'pregnancy', 'diabetes', 'copd',
       'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular',
       'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid',
       'covid_res', 'icu'],
      dtype='object')

### Note:
1. Dropping date_died column as no relation with predicting covid positive.
2. Columns- pregnancy, intubed, contct_other_covid have more than 50% null values so dropping

In [ ]:
df=df.drop(columns=['date_died','pregnancy','contact_other_covid','intubed','icu'])

## Feature Extraction from date_symptom and entry_date

In [4]:
df['delta']=abs(df['entry_date']-df['date_symptoms'])
df.loc[1,'delta']
df['delta'] = df['delta'].dt.days.astype('int16')  #Converting Timedelta type to integer days
df['delta']

0          60
1           2
2         152
3         170
4           0
         ... 
499687      6
499688      5
499689      3
499690      2
499691      8
Name: delta, Length: 499692, dtype: int16

### Note:
1. Dropping columns entry_date and date_symptoms

In [5]:
df=df.drop(columns=['entry_date','date_symptoms'])

In [9]:
df.columns

496291


Index(['sex', 'patient_type', 'age', 'pneumonia', 'diabetes', 'copd', 'asthma',
       'inmsupr', 'hypertension', 'other_disease', 'cardiovascular', 'obesity',
       'renal_chronic', 'tobacco', 'covid_res', 'delta'],
      dtype='object')

### Note:
There are few Null values present in columns that are categorical variables so we will drop Null values

In [10]:
df=df.dropna()

In [11]:
len(df)

496291

In [12]:
df

sex  patient_type  age pneumonia diabetes copd asthma inmsupr  \
0         2             1   27        No       No   No     No      No   
1         2             1   24        No       No   No     No      No   
2         1             2   54        No       No   No     No      No   
3         2             2   30       Yes       No   No     No      No   
4         1             2   60        No      Yes   No     No      No   
...     ...           ...  ...       ...      ...  ...    ...     ...   
499687    2             1   77       Yes       No   No     No      No   
499688    2             2   63       Yes       No   No     No      No   
499689    1             1   25        No       No   No     No      No   
499690    1             1   45        No       No   No     No      No   
499691    1             1   51        No       No   No     No      No   

       hypertension other_disease cardiovascular obesity renal_chronic  \
0                No            No             No      No            No   
1                No            No             No      No            No   
2                No            No             No     Yes            No   
3                No            No             No      No            No   
4               Yes            No            Yes      No            No   
...             ...           ...            ...     ...           ...   
499687           No           Yes             No      No            No   
499688          Yes            No             No     Yes            No   
499689           No            No             No      No            No   
499690          Yes            No             No      No            No   
499691           No            No             No      No            No   

       tobacco covid_res  delta  
0           No  Positive     60  
1           No  Positive      2  
2           No  Positive    152  
3           No  Positive    170  
4           No  Positive      0  
...        ...       ...    ...  
499687     Yes  Negative      6  
499688     Yes  Negative      5  
499689      No  Negative      3  
499690      No  Negative      2  
499691      No  Negative      8  

[496291 rows x 16 columns]

In [13]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [58]:
X_=df[['sex', 'patient_type', 'pneumonia', 'diabetes', 'copd', 'asthma',
       'inmsupr', 'hypertension', 'other_disease', 'cardiovascular', 'obesity',
       'renal_chronic', 'tobacco']]
X_

sex  patient_type pneumonia diabetes copd asthma inmsupr hypertension  \
0         2             1        No       No   No     No      No           No   
1         2             1        No       No   No     No      No           No   
2         1             2        No       No   No     No      No           No   
3         2             2       Yes       No   No     No      No           No   
4         1             2        No      Yes   No     No      No          Yes   
...     ...           ...       ...      ...  ...    ...     ...          ...   
499687    2             1       Yes       No   No     No      No           No   
499688    2             2       Yes       No   No     No      No          Yes   
499689    1             1        No       No   No     No      No           No   
499690    1             1        No       No   No     No      No          Yes   
499691    1             1        No       No   No     No      No           No   

       other_disease cardiovascular obesity renal_chronic tobacco  
0                 No             No      No            No      No  
1                 No             No      No            No      No  
2                 No             No     Yes            No      No  
3                 No             No      No            No      No  
4                 No            Yes      No            No      No  
...              ...            ...     ...           ...     ...  
499687           Yes             No      No            No     Yes  
499688            No             No     Yes            No     Yes  
499689            No             No      No            No      No  
499690            No             No      No            No      No  
499691            No             No      No            No      No  

[496291 rows x 13 columns]

In [61]:
oe.fit(X_)
X_=oe.transform(X_)
#X_

In [62]:
X_

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [63]:
import numpy as np
arr=np.array(df[['delta','age']])
arr

array([[ 60,  27],
       [  2,  24],
       [152,  54],
       ...,
       [  3,  25],
       [  2,  45],
       [  8,  51]], dtype=int64)

In [64]:
arr_=arr.reshape(496291,2)
X=np.append(arr_,X_,axis=1)
X

array([[ 60.,  27.,   1., ...,   0.,   0.,   0.],
       [  2.,  24.,   1., ...,   0.,   0.,   0.],
       [152.,  54.,   0., ...,   1.,   0.,   0.],
       ...,
       [  3.,  25.,   0., ...,   0.,   0.,   0.],
       [  2.,  45.,   0., ...,   0.,   0.,   0.],
       [  8.,  51.,   0., ...,   0.,   0.,   0.]])

In [125]:
y=np.array(df['covid_res'])
y=y.reshape(-1,1)
oe.fit(y)
y=oe.transform(y)
# y.reshape(496291,1)
print(type(y))
y

<class 'numpy.ndarray'>


array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [20]:
X

array([[ 60.,  27.,   1., ...,   0.,   0.,   0.],
       [  2.,  24.,   1., ...,   0.,   0.,   0.],
       [152.,  54.,   0., ...,   1.,   0.,   0.],
       ...,
       [  3.,  25.,   0., ...,   0.,   0.,   0.],
       [  2.,  45.,   0., ...,   0.,   0.,   0.],
       [  8.,  51.,   0., ...,   0.,   0.,   0.]])

### Standard Scalar
Standardizes data such that mean = 0 and standard deviation = 1

In [76]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X=scaler.transform(X)


In [88]:
print(X.std())
print(X.shape)
X

0.9999999999999966
(496291, 15)


array([[ 0.17063051, -0.93319815,  0.98814779, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [-0.71338558, -1.11366638,  0.98814779, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [ 1.57286293,  0.69101592, -1.01199437, ...,  2.25835415,
        -0.14290986, -0.3068147 ],
       ...,
       [-0.69814393, -1.0535103 , -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [-0.71338558,  0.14961123, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [-0.62193564,  0.51054769, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ]])

In [89]:
from sklearn.model_selection import train_test_split
#Split into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [90]:
X_test

array([[ 2.06059595, -0.39179346, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [-0.7438689 , -0.45194954, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [-0.6371773 ,  1.41288883, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       ...,
       [ 1.58810459, -0.51210561, -1.01199437, ...,  2.25835415,
        -0.14290986, -0.3068147 ],
       [ 0.65836353,  1.47304491, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ],
       [-0.27137754, -0.57226169, -1.01199437, ..., -0.44280035,
        -0.14290986, -0.3068147 ]])

# Classification
### Importing Important parameters

In [91]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

## 1. Logistic Regression

In [93]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\aa\Anaconda3_2020\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression()

In [114]:
#lr.score(X_train,y_train)  # predicts overall accuracy using Rsquare metrix 

In [113]:
y_test_pred = lr.predict(X_test)
y_train_pred = lr.predict(X_train)
print("Train accuracy:- \t",round(precision_score(y_train_pred,y_train)*100,2))
print("Test accuracy:- \t",round(accuracy_score(y_test_pred,y_test)*100,2))
print("Recall:- \t",round(recall_score(y_test_pred,y_test)*100,2))
print("Precision:- \t",round(precision_score(y_test_pred,y_test)*100,2))
print('F1 score:- \t',round(f1_score(y_test,y_test_pred)*100,2))


Train accuracy:- 	 37.28
Test accuracy:- 	 63.2
Recall:- 	 64.45
Precision:- 	 37.25
F1 score:- 	 47.21


In [155]:
confusion_matrix(y_test_pred,y_test)

array([[76550, 45404],
       [14870, 26953]], dtype=int64)

## 2. Decision Trees

In [156]:
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT.fit(X_train, y_train)

DecisionTreeClassifier()

In [157]:
y_test_pred = DT.predict(X_test)
y_train_pred = DT.predict(X_train)
print("Train accuracy:- \t",round(precision_score(y_train_pred,y_train)*100,2))
print("Test accuracy:- \t",round(accuracy_score(y_test_pred,y_test)*100,2))
print("Recall:- \t",round(recall_score(y_test_pred,y_test)*100,2))
print("Precision:- \t",round(precision_score(y_test_pred,y_test)*100,2))
print('F1 score:- \t',round(f1_score(y_test,y_test_pred)*100,2))

Train accuracy:- 	 57.73
Test accuracy:- 	 60.27
Recall:- 	 57.48
Precision:- 	 38.67
F1 score:- 	 46.24


In [158]:
confusion_matrix(y_test_pred,y_test)

array([[70724, 44376],
       [20696, 27981]], dtype=int64)

## 3. Decision Forest Classifier

In [160]:
from sklearn.ensemble import RandomForestClassifier
Rf = RandomForestClassifier()
Rf.fit(X_train, y_train)

<ipython-input-160-d7f3402c93b3>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  Rf.fit(X_train, y_train)


RandomForestClassifier()

In [162]:
y_test_pred = Rf.predict(X_test)
y_train_pred = Rf.predict(X_train)
print("Train accuracy:- \t",round(precision_score(y_train_pred,y_train)*100,2))
print("Test accuracy:- \t",round(accuracy_score(y_test_pred,y_test)*100,2))
print("Recall:- \t",round(recall_score(y_test_pred,y_test)*100,2))
print("Precision:- \t",round(precision_score(y_test_pred,y_test)*100,2))
print('F1 score:- \t',round(f1_score(y_test,y_test_pred)*100,2))
confusion_matrix(y_test,y_test_pred)

Train accuracy:- 	 61.88
Test accuracy:- 	 60.97
Recall:- 	 57.68
Precision:- 	 43.77
F1 score:- 	 49.77


array([[68185, 23235],
       [40688, 31669]], dtype=int64)

Lets try all the classification with a determining probabilistic threshold

### Following Function returns optimized threshold probability

In [92]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
def opt(y_train,y_train_pred):
    f1=0
    thres=10
    for threshold in range(5,90):
        thr=threshold/100
        pred_bool = ((y_train_pred)>thr)
        y=np.multiply(pred_bool, 1)
        m=recall_score(y_train,y)*accuracy_score(y_train,y)
        if m>f1:
            thres=thr
            f1=m
#             print(1)
    pred_bool = ((y_train_pred)>thres)
    y=np.multiply(pred_bool, 1)
    print('Threshold: ',thres,'Recall: ',recall_score(y_train,y))
    return y

## 1.  Logistic Regression

In [196]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train,y_train)
y_test_pred = clf.predict_proba(X_test)
y_train_pred=clf.predict_proba(X_train)
y_train_pred=y_train_pred[:,0]
y_train_pred=opt(y_train,y_train_pred)


C:\Users\aa\Anaconda3_2020\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


Threshold:  0.05 Recall:  1.0


In [197]:
y_test_pred

array([[0.59359095, 0.40640905],
       [0.6838334 , 0.3161666 ],
       [0.40938019, 0.59061981],
       ...,
       [0.53323784, 0.46676216],
       [0.27709988, 0.72290012],
       [0.67564453, 0.32435547]])

In [198]:
pred_bool = ((y_test_pred)>0.05)
y_test_pred=np.multiply(pred_bool, 1)[:,0]
print("Train Accuracy:- \t",accuracy_score(y_train, y_train_pred))
print("Test Accuracy:- \t",accuracy_score(y_test, y_test_pred))
print('Recall:- \t',recall_score(y_test,y_test_pred))
print('Precision:- \t',precision_score(y_test,y_test_pred))
print('F1 score:- \t',f1_score(y_test,y_test_pred))
confusion_matrix(y_test_pred,y_test)

Train Accuracy:- 	 0.4407182855458718
Test Accuracy:- 	 0.44180196242451625
Recall:- 	 1.0
Precision:- 	 0.44180196242451625
F1 score:- 	 0.6128469428375414


array([[    0,     0],
       [91420, 72357]], dtype=int64)

## 2. Decision Trees

In [206]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [203]:
y_test_pred = clf.predict_proba(X_test)
y_train_pred=clf.predict_proba(X_train)
y_train_pred=y_train_pred[:,0]
y_train_pred=opt(y_train,y_train_pred)

Threshold:  0.05 Recall:  0.595428025521171


In [205]:
y_test_pred

array([1, 1, 0, ..., 1, 1, 1])

In [204]:
pred_bool = ((y_test_pred)>0.05)
y_test_pred=np.multiply(pred_bool, 1)[:,0]
print("Train Accuracy:- \t",accuracy_score(y_train, y_train_pred))
print("Test Accuracy:- \t",accuracy_score(y_test, y_test_pred))
print('Recall:- \t',recall_score(y_test,y_test_pred))
print('Precision:- \t',precision_score(y_test,y_test_pred))
print('F1 score:- \t',f1_score(y_test,y_test_pred))
confusion_matrix(y_test_pred,y_test)

Train Accuracy:- 	 0.26241601857365404
Test Accuracy:- 	 0.4025046251915715
Recall:- 	 0.7390024462042373
Precision:- 	 0.4037359467846545
F1 score:- 	 0.5221875


array([[12449, 18885],
       [78971, 53472]], dtype=int64)

## 3. Decision Forest

In [207]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf = clf.fit(X_train, y_train)

<ipython-input-207-ad55e8953be3>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf = clf.fit(X_train, y_train)


In [208]:
y_test_pred = clf.predict_proba(X_test)
y_train_pred=clf.predict_proba(X_train)
y_train_pred=y_train_pred[:,0]
y_train_pred=opt(y_train,y_train_pred)

Threshold:  0.05 Recall:  0.8659046709201952


In [209]:
y_test_pred

array([[0.64590719, 0.35409281],
       [0.78656097, 0.21343903],
       [0.07      , 0.93      ],
       ...,
       [0.55792452, 0.44207548],
       [0.49411905, 0.50588095],
       [0.62089381, 0.37910619]])

In [210]:
pred_bool = ((y_test_pred)>0.05)
y_test_pred=np.multiply(pred_bool, 1)[:,0]
print("Train Accuracy:- \t",accuracy_score(y_train, y_train_pred))
print("Test Accuracy:- \t",accuracy_score(y_test, y_test_pred))
print('Recall:- \t',recall_score(y_test,y_test_pred))
print('Precision:- \t',precision_score(y_test,y_test_pred))
print('F1 score:- \t',f1_score(y_test,y_test_pred))
confusion_matrix(y_test_pred,y_test)

Train Accuracy:- 	 0.38162002201411066
Test Accuracy:- 	 0.4243269812000464
Recall:- 	 0.9341736113990353
Precision:- 	 0.43022537918568166
F1 score:- 	 0.5891314768815097


array([[ 1901,  4763],
       [89519, 67594]], dtype=int64)